---
version: '3.3'

configs:
  consul_server_config:
    file: ./consul/data/server_config.json
  consul_agent_config:
    file: ./consul/data/agent_config.json
  common_config:
    file: ./consul/data/common.json
  vault_config:
    file: ./vault/data/config/vault.json

secrets:
  consul_ca_file.cer:
    file: ./consul/data/certificates/consul-root.cer
  consul_cert_file.cer:
    file: ./consul/data/certificates/consul-server.cer
  consul_key_file.key:
    file: ./consul/data/certificates/consul-server.key
  consul_secrets_config.json:
    file: ./consul/data/secrets_config.json
  vault_cert_file.crt:
    file: ./vault/data/swarm_certs/wildcard.crt
  vault_key_file.key:
    file: ./vault/data/swarm_certs/wildcard.key
  vault_tls_ca_file.cer:
    file: ./consul/data/certificates/consul-root.cer
  vault_tls_cert_file.cer:
    file: ./consul/data/certificates/consul-server.cer
  vault_tls_key_file.key:
    file: ./consul/data/certificates/consul-server.key

networks:
  vault-network:

volumes:
  vault-volume:
    labels:
      - "gov.usgs.wma.docker.description=Hashicorp Vault Docker Volume"
      - "gov.usgs.wma.docker.name=volume.vault"

services:
  consul_agent:
    image: consul:0.9.3
    networks:
      vault-network:
        aliases:
          - agent.consul.swarm.container
    command: "consul agent -config-dir=/data/config -config-file=/run/secrets/consul_secrets_config.json"
    ports:
      - "8701:8701"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: pause
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
    configs:
      - source: common_config
        target: /data/config/node_swarm_config.json
      - source: consul_agent_config
        target: /data/config/config.json
    secrets:
      - consul_ca_file.cer
      - consul_cert_file.cer
      - consul_key_file.key
      - consul_secrets_config.json

  consul_server:
    image: consul:0.9.3
    networks:
      vault-network:
        aliases:
          - server.consul.swarm.container
    command: "consul agent -config-dir=/data/config -config-file=/run/secrets/consul_secrets_config.json"
    ports:
      - "8700:8700"
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        failure_action: pause
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
    configs:
      - source: common_config
        target: /data/config/node_swarm_config.json
      - source: consul_server_config
        target: /data/config/config.json
    secrets:
      - consul_ca_file.cer
      - consul_cert_file.cer
      - consul_key_file.key
      - consul_secrets_config.json
  
  vault:
    image: vault:0.8.3
    networks:
      vault-network:
        aliases:
          - vault.swarm.container
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    ports:
      - "8200:8200"
      - "8201:8201"
      - "8125:8125"
    environment:
      - VAULT_REDIRECT_INTERFACE=eth2
      - VAULT_CLUSTER_INTERFACE=eth2
    command: "vault server -config=/vault/config/vault.json"
    configs:
      - source: vault_config
        target: /vault/config/vault.json
    secrets:
      - vault_cert_file.crt
      - vault_key_file.key
      - vault_tls_ca_file.cer
      - vault_tls_cert_file.cer
      - vault_tls_key_file.key

  vault_ui:
    image: djenriquez/vault-ui:2.3.0
    networks:
      vault-network:
        aliases:
          - vault.ui.container
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    ports:
      - "8000:8000"
    environment:
      - VAULT_URL_DEFAULT=https://vault.swarm.container:8200
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PORT=8000
