---
version: '3'

networks:
  vault-network:

volumes:
  dynamodb-volume:
    labels:
      - "gov.usgs.wma.docker.description=DynamoDB Docker Volume"
      - "gov.usgs.wma.docker.name=volume.dynamodb"
  vault-volume:

services:
  dynamodb:
    build:
      context: ./dynamodb
    container_name: vault_dynamodb
    image: vault_dynamodb
    networks:
      vault-network:
        aliases:
          - dynamodb
    ports:
      - "8000:${DYNAMODB_PORT:-8000}"
    volumes:
      - dynamodb-volume:/dynamodb_local_db
    command: "-Djava.library.path=. -jar DynamoDBLocal.jar --sharedDb -optimizeDbBeforeStartup -dbPath /dynamodb_local_db -port ${DYNAMODB_PORT:-8000} -cors ${DYNAMODB_CORS:-*}"
    env_file:
      - "./dynamodb/compose${DOCKER_DYNAMODB_ENV_LOCAL}.env"

  vault:
    build:
      context: ./vault
    container_name: vault
    image: vault_dev
    networks:
      vault-network:
        aliases:
          - vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:${VAULT_SERVER_PORT:-8200}"
      - "8201:${VAULT_CLUSTER_PORT:-8201}"
      - "8125:${VAULT_TELEMETRY_PORT:-8125}"
    volumes:
      - "vault-volume:/vault/logs"
      - "vault-volume:/vault/file"
      - "./vault/data/config:/vault/config"
    command: "vault server -config=/vault/config/local.json"
    env_file:
      - "./vault/compose${DOCKER_VAULT_ENV_LOCAL}.env"
    depends_on:
      - dynamodb
