---
version: '3.3'

networks:
  vault-network:

volumes:
  dynamodb-volume:
    labels:
      - "gov.usgs.wma.docker.description=DynamoDB Docker Volume"
      - "gov.usgs.wma.docker.name=volume.dynamodb"
  vault-volume:
    labels:
      - "gov.usgs.wma.docker.description=Hashicorp Vault Docker Volume"
      - "gov.usgs.wma.docker.name=volume.vault"

services:
  consul_node_1:
    image: consul:0.8.5
    container_name: vault_consul_node1
    networks:
      vault-network:
        aliases:
          - consul.1.container
    volumes:
      - "./consul/data/:/data"
    command: "consul agent -config-file=/data/node1_config.json"
    ports:
      - "8500:8500"
      - "8700:8700"
  consul_node_2:
    image: consul:0.8.5
    container_name: vault_consul_node2
    networks:
      vault-network:
        aliases:
          - consul.2.container
    volumes:
      - "./consul/data/:/data"
    command: "consul agent -config-file=/data/node2_config.json"
    ports:
      - "8501:8500"
      - "8701:8701"
    depends_on:
      - consul_node_1
  consul_node_3:
    image: consul:0.8.5
    container_name: vault_consul_node3
    networks:
      vault-network:
        aliases:
          - consul.3.container
    volumes:
      - "./consul/data/:/data"
    command: "consul agent -config-file=/data/node3_config.json"
    ports:
      - "8502:8500"
      - "8702:8702"
    depends_on:
      - consul_node_1

  dynamodb:
    build:
      context: ./dynamodb
    container_name: vault_dynamodb
    image: vault_dynamodb
    networks:
      vault-network:
        aliases:
          - dynamodb
    ports:
      - "8000:${DYNAMODB_PORT:-8000}"
    volumes:
      - dynamodb-volume:/dynamodb_local_db
    command: "-Djava.library.path=. -jar DynamoDBLocal.jar --sharedDb -optimizeDbBeforeStartup -dbPath /dynamodb_local_db -port ${DYNAMODB_PORT:-8000} -cors ${DYNAMODB_CORS:-*}"
    env_file:
      - "./dynamodb/compose${DOCKER_DYNAMODB_ENV_LOCAL}.env"

  vault1:
    build:
      context: ./vault
    container_name: vault1
    image: vault_dev
    networks:
      vault-network:
        aliases:
          - vault1.container
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:${VAULT1_SERVER_PORT:-8200}"
      - "8201:${VAULT1_CLUSTER_PORT:-8201}"
      - "8125:${VAULT1_TELEMETRY_PORT:-8125}"
    volumes:
      - "vault-volume:/vault/logs"
      - "vault-volume:/vault/file"
      - "./vault/data/config:/vault/config"
      - "./vault/data/certs:/vault/certs"
    command: "vault server -config=/vault/config/vault1.json"
    env_file:
      - "./vault/vault1_compose${DOCKER_VAULT1_ENV_LOCAL}.env"
    depends_on:
      - dynamodb

  vault2:
    build:
      context: ./vault
    container_name: vault2
    image: vault_dev
    networks:
      vault-network:
        aliases:
          - vault2.container
    cap_add:
      - IPC_LOCK
    ports:
      - "8202:${VAULT2_SERVER_PORT:-8200}"
      - "8203:${VAULT2_CLUSTER_PORT:-8201}"
      - "8126:${VAULT2_TELEMETRY_PORT:-8125}"
    volumes:
      - "vault-volume:/vault/logs"
      - "vault-volume:/vault/file"
      - "./vault/data/config:/vault/config"
      - "./vault/data/certs:/vault/certs"
    command: "vault server -config=/vault/config/vault1.json"
    env_file:
      - "./vault/vault2_compose${DOCKER_VAULT2_ENV_LOCAL}.env"
    depends_on:
      - dynamodb

  vault3:
    build:
      context: ./vault
    container_name: vault3
    image: vault_dev
    networks:
      vault-network:
        aliases:
          - vault3.container
    cap_add:
      - IPC_LOCK
    ports:
      - "8204:${VAULT3_SERVER_PORT:-8200}"
      - "8205:${VAULT3_CLUSTER_PORT:-8201}"
      - "8127:${VAULT3_TELEMETRY_PORT:-8125}"
    volumes:
      - "vault-volume:/vault/logs"
      - "vault-volume:/vault/file"
      - "./vault/data/config:/vault/config"
      - "./vault/data/certs:/vault/certs"
    command: "vault server -config=/vault/config/vault3.json"
    env_file:
      - "./vault/vault3_compose${DOCKER_VAULT3_ENV_LOCAL}.env"
    depends_on:
      - dynamodb
